name: Automerge Pull Request

on:
  pull_request:
    types:
      - synchronize
      - opened
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "shivamnaik6574@gmail.com"
          git config user.name "shivamnaik6574"

      - name: Automerge Pull Request
        uses: pascalgn/automerge-action@v0.14.0
        with:
          token: ${{ secrets.TOKEN }}
