name: Create PRs for Commit IDs

on:
  push:
    branches:
      - main

jobs:
  create_prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "shivamnaik6574@gmail.com"
          git config --global user.name "shivamnaik6574"

      - name: Get Latest PR Numbers
        id: get_pr_numbers
        run: |
          OWNER="shivamnaik6574"
          REPO="auto-merge"
          PR_NUMBERS=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            "https://github.com/$OWNER/$REPO/commits/main/" | \
            jq -r '.[].number' | head -n 100)
          echo "::set-output name=pr_numbers::$PR_NUMBERS"

      - name: Create PRs for Commit IDs
        run: |
          PR_NUMBERS="${{ steps.get_pr_numbers.outputs.pr_numbers }}"
          for PR_NUMBER in $PR_NUMBERS
          do
            COMMIT_ID=$(curl -s -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUMBER" | \
              jq -r '.head.sha')
            
            # Create a pull request for each commit ID
            gh pr create --base main --head "$COMMIT_ID" --title "Automated PR for Commit $COMMIT_ID" --body "This PR is automatically generated for commit $COMMIT_ID."
          done
